# run_sim_count: num of simulations for test runs
# train_sim_count: total num of simulations for model training
# sim_count_per_train: num of simulations per training iteration
# traj_per_cluster: percent of trajectories selected from each cluster
# steps: num of time steps per simulation
# sd: standard deviation for cps coverage score


automatic_transmission:
  dt: 0.01
  sd: [1, 50]
  steps: 100
  cluster_count: 10
  run_sim_count: 100
  train_sim_count: 200
  traj_per_cluster: 0.5
  sim_count_per_train: 100
  inputs_lower_bound: [0, 0]
  inputs_upper_bound: [100, 350]
  init_state: [0.0, 0.0, 1.0]